### ISSUE TITLE
make jokers more permissible

### ISSUE THREAD

**Issue by assem-ch** [Alfanous-team/alfanous#242]
- 2 asterisks
  (http://www.alfanous.org/?query=+%28%D8%A7%D9%84*%D9%88%D9%86%29%7C%28%D8%A7%D9%84*%D9%8A%D9%86%29&view=default&sortedby=score&translation=en.transliteration&recitation=14 )

**Comment by b1go** [comment]
if users had to use asterisks , ie your search is not good enough
