### ISSUE TITLE
Packaging AlfanousDesktop to MAC

### ISSUE THREAD

**Issue by assem-ch** [Alfanous-team/alfanous#26]

**Comment by assem-ch** [comment]
Pyinstaller is a good tool to do this , and it works for windows too (2 birds with one stone)

http://pythonhosted.org/PyInstaller/

**Comment by sneetsher** [comment]
This packaging topic is really a headache. It takes too much time and resources for divergent paths. Even if we could package it, we may not able to maintain it.  Multiple dependency types (It's not pure Python)  and versions (like with Django==1.5.1).

I'm not aware about PyInstaller, however if we can get Alfanous to install from source through Homebrew. Which looks to me as the easiest path or build full bundle.

This is my report when installing Alfanous from source

```
# building dependencies
pip install pyparsing epydoc sphinx

brew tap cartr/qt4
brew tap-pin cartr/qt4
brew install qt@4
brew install qt-webkit@2.3  

brew install pyside-tools
brew install pyside

# only used for installing pyside using pip
brew install cmake

# todo: fix it in Makefile to check for lrelease
ln /usr/local/bin/lrelease /usr/local/bin/lrelease-qt4

make build
sudo make install_api_no_arguments

sudo make install_desktop_no_arguments
# todo: alfanous is installing pyside using pip, It didn't detect brew installed one
# todo: desktop installation fails because it tries to use GNU/Linux system folder structure like '/usr/share/applications/'

# only for web interface
pip install django==1.5.1
```

. build: OK, no issues.
. alfanous-console: installed and runs OK
. alfanous-django: run OK
. alfanous-desktop: installation fails, but runs OK

**Comment by assem-ch** [comment]
we only need to package alfanous-desktop for users, and we can chagrge users a small amount for maintainance.
