### ISSUE TITLE
Structuration of webpage results under headers h1,h2,h3,h4

### ISSUE THREAD

**Issue by assem-ch** [Alfanous-team/alfanous#394]
This will be useful for Search engines.

h1 should be unique

**Comment by assem-ch** [comment]
@sneetsher

**Comment by sneetsher** [comment]
I am with @assem-ch  as you said:

> yes only one h1 for the page , an i think h2 for query section, keywords, suggestions, aya results ... and h3 for each aya result

- h1 Alfanous (logo) , I just checked google & yahoo
- h2 Query text
- h3 Result item (Ayah/translation..)
