### ISSUE TITLE
Implement Alfanous Search in "Quran for android app"

### ISSUE THREAD

**Issue by assem-ch** [Alfanous-team/alfanous#426]
https://play.google.com/store/apps/details?id=com.quran.labs.androidquran

**Comment by sneetsher** [comment]
@assem-ch could you put short comments when we close an issue? So we know what blocks us from fixing it and when we could reopen it.

**Comment by assem-ch** [comment]
You're right 

For this issue, using Alfanous search in third-party apps is not part of Alfanous project, the idea was to show the search power of Alfanous, but we can do it through the webapp or internal webapp and it's almost done. This issue could be re-opened in `Quran for android app` repo or as an independent project.
