### ISSUE TITLE
Testing AlfanousDesktop in windows 7-8

### ISSUE THREAD

**Issue by assem-ch** [Alfanous-team/alfanous#430]
(tested by @zsmahi )

- [x] Alerte lors du téléchargement
Une alerte s'est déclenchée lors le téléchargement du package (IExplorer 11, Google Chrome).
Solution : Forcer l'installation 

- [x]  1er test recherche simple 'default'
Search " الحمد لله "
Résultats : 116

- [x]   Langues :
La seule langue active est l'anglais; lors du test de changement de la langue, certes qu'on a le message de confirmation de changement de la langue et de de confirmation de redémarrage pour valider les changements, mais après seule la langue anglaise est active.
Voir Screenshoot suivant
![image](https://cloud.githubusercontent.com/assets/315228/6313691/49faec60-b9ba-11e4-881f-c9b724101342.png)

Langue choisie : français , langue affichée : anglais.
- [x]  Thèmes : Skin
Thème Macintosh : ne fonctionne pas sous Windows.
Problème lors de l’application des skins CDE, Motif : Les éléments UI ne s’affichent pas correctement (disabled style).

![image](https://cloud.githubusercontent.com/assets/315228/6313691/49faec60-b9ba-11e4-881f-c9b724101342.png)

- [x] No results when unchecking Option-> Show-> Keyword info

**Comment by assem-ch** [comment]
@zsmahi I uploaded a new version of windows installer, can you test it http://sourceforge.net/projects/alfanous/files/Interfaces/AlfanousDesktop/alfanousInstallerV0.7.10.exe/download

**Comment by zsmahi** [comment]
Yes It worked for me ; I've tested english and arabic languages , for french it doesn't change is it disabled for the moment ?

**Comment by assem-ch** [comment]
no French translation for now

**Comment by Zinebl** [comment]
@assem-ch instl and global display are ok, also items (verb, noun, pr) in words properties panel are correct, but the button "add to search br" in this panel didn't work

**Comment by assem-ch** [comment]
@zsmahi strange! I will check with that
