### ISSUE TITLE
Port the web application to the latest Django version

### ISSUE THREAD

**Issue by abougouffa** [Alfanous-team/alfanous#448]
alfanous-django require (Django==1.5.1) and can't run on newer version
https://docs.djangoproject.com/en/1.8/internals/deprecation

**Comment by assem-ch** [comment]
@abougouffa Thanks  for submitting. Actually it's running on 1.5.1. To fix that, I suggest  to port it version by version: 1.6 to 1.7  to 1.8.  Since web hosts don't include new version quickly, I suggest porting only to 1.6 or 1.7.
