### ISSUE TITLE
أين نسخة الويب في الكود ! مسارها لم أكد أجده ! 

### ISSUE THREAD

**Issue by ayoubnaceur** [Alfanous-team/alfanous#450]
لم أجد نسخة الويب المماثلة لما تظهر عليه الصفحة الرئيسية في alfanous.org/ar/
أين هو الأنديكس ، و أين هي الستايلز ؟

**Comment by assem-ch** [comment]
هي مبنية على django framework وبالتالي لن تجد index.html 

بل ستجد تطبيقا يتم تشغيله بال cgi

Style here: 
https://github.com/Alfanous-team/alfanous/tree/master/src/alfanous-django/wui/static/shared
