### ISSUE TITLE
Scrambled ayah's words in desktop GUI in Mac OS

### ISSUE THREAD

**Issue by sneetsher** [Alfanous-team/alfanous#480]
Quran Arabic words are not aligned vertically. It seems a font/shaping-engine issue. See screenshot:

<img width="1225" alt="alfanous-desktop-macos10 13" src="https://user-images.githubusercontent.com/1183049/40272943-f57739a6-5bae-11e8-8ce6-6c376339d643.png">

**Comment by assem-ch** [comment]
@sneetsher did you try to change the font family or size?

**Comment by sneetsher** [comment]
Same issue but less It could be WebKit rendering issue (each word is in a span/a tag)

By the way, did you disable 2 fonts on purpose:
```

--- a/src/alfanous-desktop/templates/aya_results.html
+++ b/src/alfanous-desktop/templates/aya_results.html
@@ -67,12 +67,12 @@ padding:12px;
 
 @font-face {
     font-family:'me_quran';
-    src:url('qrc:/fonts/fonts/me_quran_volt_mark2.ttf');
+    src:url('qrc:/fonts/me_quran_volt_mark2.ttf');
 }
 
 @font-face {
     font-family:'ArabeyesQr';
-    src:url('qrc:/fonts/fonts/arabeyes-qr.ttf');
+    src:url('qrc:/fonts/arabeyes-qr.ttf');
 } 
```

<img width="1280" alt="alfanous-desktop_macos10 13_another_font" src="https://user-images.githubusercontent.com/1183049/40354008-c79e9508-5daa-11e8-8c14-06f3b7f7359e.png">
