### ISSUE TITLE
 'tuple' object has no attribute 'runtime' - error from word search in WUI

### ISSUE THREAD

**Issue by sneetsher** [Alfanous-team/alfanous#482]
My query: 

http://alfanous.org/en/word/?query=الله

No result is showed and got the following error message:

> Error (-1) : fail, reason unknown
> 'tuple' object has no attribute 'runtime'
> 
> please submit that as a bug here: feedback.alfanous.org! 

JSON:
```
{
    "error": {
        "msg": "fail, reason unknown\n'tuple' object has no attribute 'runtime'\n\n please submit that as a bug here: feedback.alfanous.org!", 
        "code": -1
    }
}
```
Btw, I don't have word search active in my local dev copy.

**Comment by assem-ch** [comment]
fixed, in #483
