### ISSUE TITLE
Some notes about SEO PR

### ISSUE THREAD

**Issue by assem-ch** [Alfanous-team/alfanous#486]
the bullet before keywords is unessassry and I suggest to replace bullet with any separator symbol .

result  number and aya id should be in the same line, no?

<img width="1016" alt="screen shot 2018-05-25 at 2 19 48 am" src="https://user-images.githubusercontent.com/315228/40521347-1203bd7a-5fc3-11e8-9d62-07f6fe99d381.png">

**Comment by assem-ch** [comment]
1.  Yes,  dont care lot about translation, it will follow

2. Chrome

**Comment by sneetsher** [comment]
1. Ok I go for it (I rewrite it to separate counted nouns needed for correct i18n)
2. `style.css` is not updated in the server.

**Comment by assem-ch** [comment]
2.  is the new style.css commited to master?

**Comment by sneetsher** [comment]
yes @assem-ch

**Comment by assem-ch** [comment]
done, updated
