### ISSUE TITLE
Keyboard view not works as well as expected

### ISSUE THREAD

**Issue by muslih** [Alfanous-team/alfanous#496]
I recently try to open the keyboard by clicking keyboard icon on search bar, and it seems not working at this moment.

![screen recording 2018-05-26 at 12 24 am](https://user-images.githubusercontent.com/2532862/40557725-407b8102-607b-11e8-9033-46b23b76420c.gif)

cc @Alfanous-team/developers

**Comment by assem-ch** [comment]
@muslih thank you for reporting, 

@sneetsher there is issue with closing div tags , and <main> tag:

https://validator.w3.org/nu/?doc=http%3A%2F%2Falfanous.org%2Ftr%2Faya%2F%3Fquery%3D%25D9%2581%25D9%2588%25D9%2584%25D9%2584%26fuzzy%3DTrue%26view%3Ddefault%26sortedby%3Dscore%26translation%3Den.transliteration%26recitation%3D14%26advanced_search_advanced_query_optionsRadios%3Dphrase

**Comment by muslih** [comment]
@assem-ch sometimes it works, but only once, when the keyboard closed it and open again for second times it doesn't works

**Comment by assem-ch** [comment]
@muslih I noticed that, when the search input is under focus it doesnt show .. ping @sneetsher

**Comment by sneetsher** [comment]
@assem-ch I will check it. May be my added `main` tag.

(off-topic: I was using vim which does track html tags, not quite familiar tools available in mac os. Any recommendation  for specific IDE for alfanous)

**Comment by sneetsher** [comment]
@assem-ch Could you please merge related PR and keep it open. Sync with server so user using the feature can work.

I have to get a way to validate the templates. At least, for HTML tags only. Quick review, it rewriting some parts.

Ex. an opening tag inside `if` & `else` jinja control, seen by IDE/HTML-validator as 2 opening tags.

**Comment by assem-ch** [comment]
@sneetsher pycharm match them well, I am using it he process django templates
