### ISSUE TITLE
Add Bengali language as translation

### ISSUE THREAD

**Issue by suman249** [Alfanous-team/alfanous#517]
Please, could you add Bengali translation.

**Comment by sneetsher** [comment]
Welcome to Alfanous. The project have few core developers and AFAIK no one knows Bengali language. So this wouldn't be fixed soon. 

You are welcome to submit a pull request or send translated file directly. Or even may invite someone you know to translate it.

Just to be sure, are you asking for web interface or desktop one?

I'm going to close this one, feel free to ask opening it later, if there is an update.
