### ISSUE TITLE
Pin dynamic-rest to 1.9.6

### ISSUE THREAD

**Issue by suavesav** [Alfanous-team/alfanous#518]
We are working to deprecate Python2.7 support for `dynamic-rest` which will take effect in `dynamic-rest` version 2.0.0

To avoid downtime, we recommend, you pin your dynamic-rest version to 1.9.6 or earlier

As best practice, you should be pinning all your dependencies to the latest version that you know supports your app

**Comment by assem-ch** [comment]
thank you, its not used in this repo.
