### ISSUE TITLE
How can I directly search by surah and aya number

### ISSUE THREAD

**Issue by arfan** [Alfanous-team/alfanous#522]
How can I directly search by sura and aya number?
I am trying to do it like this https://www.alfanous.org/api/search?sura_id=1&aya_id=1 but it gives no result.

Regards

**Comment by sneetsher** [comment]
Welcome @arfan

Those keywords in [this table](https://github.com/Alfanous-team/alfanous#fields) are `query` fields, not API GET/URL parameters.

So your `search?query=sura_id:1+aya_id:1` , the same as you  type it in Alfanous website search box, ie. `sura_id:1+aya_id:1`

However  in URL, it should be encoded:

- Website interface: https://www.alfanous.org/en/aya/?query=sura_id%3A1%2Baya_id%3A1
- API: https://www.alfanous.org/api/search?query=sura_id%3A1%2Baya_id%3A1

Let me, know when you try them, if that what you wanted.

**Comment by arfan** [comment]
Thank you. The url works.

**Comment by sneetsher** [comment]
You welcome.

**Comment by Kentoseth** [comment]
This example does not work on the JOS2 version of the API.

[Same example as above](https://www.alfanous.org/jos2?query=sura_id:1+aya_id:3) results in entire Surah fati7a being shown.

How do we make API queries using this URL:

https://www.alfanous.org/jos2?

?

**Comment by sneetsher** [comment]
@Kentoseth  It does accept same query format. JOS2 is at an old API version and it is kept for compatibility. If you are developing something new, recommend sticking to edge version [https://www.alfanous.org/api/](https://www.alfanous.org/api/)

https://www.alfanous.org/jos2/search?query=sura_id%3A1%2Baya_id%3A1
