### ISSUE TITLE
List topics and subtopics

### ISSUE THREAD

**Issue by iTarek** [Alfanous-team/alfanous#525]
السلام عليكم ورحمة الله وبركاته
We can list chapters using this
https://www.alfanous.org/jos2?action=show&query=chapters

Is there is a way to list Topics and Subtopics ?

Also why this not working
https://www.alfanous.org/api/show/?query=chapters

PS: Brother this is one of kind project, please don't stop working on it.
Imagine from all muslims you are the only one who made such a project, really proud of you.

**Comment by assem-ch** [comment]
وعليكم السلام ورحمة الله وبركاته

> We can list chapters using this
> https://www.alfanous.org/jos2?action=show&query=chapters
> Is there is a way to list Topics and Subtopics ?)

no, but we can expose the topics and subtopics too

> Also why this not working
> https://www.alfanous.org/api/show/?query=chapters

You can use jos2/ , we'll keep it is alias even after fixing this logic with api/

> PS: Brother this is one of kind project, please don't stop working on it.
> Imagine from all muslims you are the only one who made such a project, really proud of you.

Thank you, bro for your encouragement, I keep do some changes from time to time , I dropped some dead weight from code just to keep things rolling.

**Comment by iTarek** [comment]
> no, but we can expose the topics and subtopics too

How to expose the topics and subtopics too? can you give example please?

**Comment by assem-ch** [comment]
https://www.alfanous.org/api/show/?query=topics
https://www.alfanous.org/api/show/?query=subtopics

**Comment by iTarek** [comment]
> https://www.alfanous.org/api/show/?query=topics
> https://www.alfanous.org/api/show/?query=subtopics

It's not working brother, try it yourself

**Comment by assem-ch** [comment]
They are not implemented yet, but it will be on those endpoints, same structure as chapters

**Comment by iTarek** [comment]
> They are not implemented yet, but it will be on those endpoints, same structure as chapters

Can you send the topics and subtopics to me as strings in file, I will hardcoded them anyway on the app

**Comment by iTarek** [comment]
I just want 2 text files
One has all topics separated by comma
Other has all subtopics separated by comma

Can you do this for me please

**Comment by b1go** [comment]
[chapter-topics.xlsx](https://github.com/Alfanous-team/alfanous/files/6744042/chapter-topics.xlsx)

here is the file, but we'll do the api anyway and by time it will be dynamic based on search results: Facets

**Comment by iTarek** [comment]
> [chapter-topics.xlsx](https://github.com/Alfanous-team/alfanous/files/6744042/chapter-topics.xlsx)
> 
> here is the file, but we'll do the api anyway and by time it will be dynamic based on search results: Facets

Thank you very much brother you will made the App allot better

جزاك الله خير
