### ISSUE TITLE
Logical relations shows not related results using API

### ISSUE THREAD

**Issue by iTarek** [Alfanous-team/alfanous#526]
Example:
https://www.alfanous.org/api/search?query=سورة:الإخلاص+أحد

And it same things on all logical relations

I did not find anyway to search on one sura using the API always give results from other suras too

Can you help and give me working API query that search on sura, I am sure it's working because the website give correct results.

**Comment by sneetsher** [comment]
Welcome. It is missing the logic keyword in the query. The supported AND logic operators are: `+` (URL encoded to `%2B`), `AND` or `و` inside `query`, Example:

1. `و`

  - Web: https://www.alfanous.org/ar/aya/?query=سورة:الإخلاص+و+أحد
  - API: https://www.alfanous.org/api/search?query=سورة:الإخلاص+و+أحد
 
2. `+`

  - Web: https://www.alfanous.org/ar/aya/?query=سورة:الإخلاص+%2B+أحد
  - API: https://www.alfanous.org/api/search?query=سورة:الإخلاص+%2B+أحد

3. `AND`

  - Web: https://www.alfanous.org/ar/aya/?query=سورة:الإخلاص+AND+أحد
  - API: https://www.alfanous.org/api/search?query=سورة:الإخلاص+AND+أحد
  
For OR logic operators: `|`, `OR` or `أو`. By the way, OR is the default logic operation, so you may drop/omit it from the query. So this works fine:

  - Web: https://www.alfanous.org/ar/aya/?query=سورة:الإخلاص+أحد
  - API: https://www.alfanous.org/api/search?query=سورة:الإخلاص+أحد

**Comment by iTarek** [comment]
Thank you, you are right just have to encode ( + ) in the url

This did the trick (Swift)
```
        urlComponents.percentEncodedQuery = urlComponents.percentEncodedQuery?
            .replacingOccurrences(of: "+", with: "%2B")
```
