### ISSUE TITLE
Why there is no donation link on the website?

### ISSUE THREAD

**Issue by iTarek** [Alfanous-team/alfanous#527]
Hello
I wonder why there is no donation link on the website, project like this have costs and people can share the cost with you, so you just have to worry about making it better.

Web site like tanzil.net, have a donation page..
https://tanzil.net/docs/donation

I wish if you make the same thing and make it easy for users to donate money.

Thank you

**Comment by assem-ch** [comment]
Hi, PayPal is not allowing donations for many countries including Algeria. 

@muslih   is it allowed in Indonesia?

**Comment by muslih** [comment]
Afaik yes, it is allowed in Indonesia @assem-ch

**Comment by zsmahi** [comment]
It is allowed in France, I can create it for Alfanous 👍

**Comment by iTarek** [comment]
You can also make it in UAE. There is many websites also use other methods website like https://nuqayah.com
uses
https://donorbox.org/

**Comment by zsmahi** [comment]
Salam alaikoum

I've made a donation link on paypal , you can use it : https://www.paypal.com/donate/?hosted_button_id=4RFAQCBNHMVRY 

Feel free to share it :)

**Comment by iTarek** [comment]
> Salam alaikoum
> 
> I've made a donation link on paypal , you can use it : https://www.paypal.com/donate/?hosted_button_id=4RFAQCBNHMVRY
> 
> Feel free to share it :)

The donation link must be added on the main web page

**Comment by b1go** [comment]
It is added to the website, orange button at the bottom

**Comment by iTarek** [comment]
> It is added to the website, orange button at the bottom

It's too small :) 
If we point the users to donate they for sure will ask where is the donation button, can't you please make it bigger under the help a good big donation button that users will never miss

**Comment by zsmahi** [comment]
Hello mates,

I've edited the previous generated link for donation (i've added alfanous's logo, and generate an html form For that)
Here is the new link: https://www.paypal.com/donate?hosted_button_id=EBKM4U5NSYV3W 


And for addingnit to the website I recommand using the paypal's autogenerated form 


Can anyone please add it ?

Here is the code

`<form action="https://www.paypal.com/donate" method="post" target="_top">
<input type="hidden" name="hosted_button_id" value="EBKM4U5NSYV3W" />
<input type="image" src="https://www.paypalobjects.com/en_US/FR/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
<img alt="" border="0" src="https://www.paypal.com/en_FR/i/scr/pixel.gif" width="1" height="1" />
</form>   `

Just copy-paste and it will work as charm.

**Comment by b1go** [comment]
@iTarek  check again

**Comment by iTarek** [comment]
> @iTarek check again

But now you removed the Help button and it was important too

**Comment by b1go** [comment]
button is added back, but we ll change it's place in the future

**Comment by iTarek** [comment]
Since we launch the iOS app few users asked us how to donate, and we forward them to your website, I wish there is a good amount of donation that keep things go.

**Comment by sneetsher** [comment]
@iTarek  that is nice.

@assem-ch I would recommend that we have a periodic public report for donation (just total, even none). It will help stabilize value quickly depending how end users evaluate the project and its needs.  My side it is better to be more than once a year.

**Comment by zsmahi** [comment]
I totally agree @sneetsher

**Comment by assem-ch** [comment]
@iTarek  there is around 250 dollars, for now, that's great for a start, we'll see how things go in the next 6 months.


@sneetsher  we'll do it yearly , or every quarter if there is enough donation to boost new features

**Comment by iTarek** [comment]
> @iTarek there is around 250 dollars, for now, that's great for a start, we'll see how things go in the next 6 months.
> 
> @sneetsher we'll do it yearly , or every quarter if there is enough donation to boost new features

If you are going to work on the project and make better I can push to get even more money, just the users who donate like to see that things changes when they donated, they trust us for sure but it will be better to show them that there money is making different.
