### ISSUE TITLE
Blank Feedback Modal

### ISSUE THREAD

**Issue by muslih** [Alfanous-team/alfanous#528]
I just tried to click a feedback button and found blank modal on firefox, it was working fine on chrome

###browser
firefox

### Preview
![image](https://user-images.githubusercontent.com/2532862/123596560-ece84780-d824-11eb-94e4-1d5350c8ea3a.png)

**Comment by sneetsher** [comment]
@muslih welcome.

It does work well for me with Firefox in macos. Do you have any Ads blocker extension active?

**Comment by muslih** [comment]
Thank you @sneetsher let me close the issue
