### ISSUE TITLE
We made a new modern logo for AlFanous

### ISSUE THREAD

**Issue by iTarek** [Alfanous-team/alfanous#529]
We updating our iOS app, so as it use modern style one of our friends created a logo for free for us... [here](https://iphoneislam.com/wp-content/uploads/2021/06/alfanous-logo-text.png) if you want to use it...

![AlFanous_Logo_Text](https://user-images.githubusercontent.com/693715/123643046-49973280-d824-11eb-9e4f-f988a91ef3a2.png)

**Comment by b1go** [comment]
I dont think we'll change colors but if you can provide the source so we can start from same logic

**Comment by iTarek** [comment]
> I dont think we'll change colors but if you can provide the source so we can start from same logic

I done have the illustrator only the png but you can change the png colors, here is example we use in dark mode
![Home_AlFanous_Logo_Dark](https://user-images.githubusercontent.com/693715/124037999-bcf59b80-da00-11eb-92ce-ebb000b124a5.png)
