### ISSUE TITLE
Can I say AlFanous uses Artificial Intelligence (AI)

### ISSUE THREAD

**Issue by iTarek** [Alfanous-team/alfanous#531]
On the advertising for the iOS app can I say AlFanous uses Artificial Intelligence (AI), or this would be lie?

Artificial intelligence (AI) is intelligence demonstrated by machines, as opposed to the natural intelligence displayed by humans or animals. Leading AI textbooks define the field as the study of "intelligent agents": any system that perceives its environment and takes actions that maximize its chance of achieving its goals.[a] Some popular accounts use the term "artificial intelligence" to describe machines that mimic "cognitive" functions that humans associate with the human mind, such as "learning" and "problem solving"
-wiki

**Comment by b1go** [comment]
NLP is a subset of AI which is used in Alfanous so it is not a lie but kind of simplification , it's related to your audience if they understand NLP or not
