### ISSUE TITLE
There is big problem most of keys in API including sura keys return as null

### ISSUE THREAD

**Issue by iTarek** [Alfanous-team/alfanous#532]
There is big problem most of keys in API including sura keys return as null
I hope you fixing this soon

```
"ayas": {
      "1": {
        "position": {},
        "aya": {
          "next_aya": {
            "text": "اللَّهُ الصَّمَدُ",
            "sura_arabic": "الإخلاص",
            "id": 2,
            "sura": "Al-Ikhlas"
          },
          "text": "قُلْ هُوَ اللَّهُ &lt;span class=\"match term0\"&gt;أَحَدٌ&lt;/span&gt;",
          "recitation": "https://www.everyayah.com/data/Abdul_Basit_Murattal_64kbps/112001.mp3",
          "prev_aya": {
            "text": "فِي جِيدِهَا حَبْلٌ مِنْ مَسَدٍ",
            "sura_arabic": "المسد",
            "id": 5,
            "sura": "Al-Masadd"
          },
          "translation": null,
          "id": 1,
          "text_no_highlight": "قل هو الله أحد"
        },
        "sura": {},
        "annotations": {},
        "sajda": {
          "id": null,
          "type": null,
          "exist": false
        },
```

**Comment by b1go** [comment]
can you explain what issue here?

**Comment by iTarek** [comment]
> can you explain what issue here?

Go yo 
https://www.alfanous.org/ar/aya/?query=الله

you will find there is no sura detail 

The sura information is empty

**Comment by iTarek** [comment]
> > can you explain what issue here?
> 
> Go yo
> [https://www.alfanous.org/ar/aya/?query=الله](https://www.alfanous.org/ar/aya/?query=%D8%A7%D9%84%D9%84%D9%87)
> 
> you will find there is no sura detail
> 
> The sura information is empty

The keys that have information about the sura like sura type guza and details are gone

**Comment by iTarek** [comment]
Please try fix this as soon as possible as I am working on the iOS app

**Comment by b1go** [comment]
it's not a bug, it is just we dont show sura info by default. You can add `view=normal` to get it or `sura_info=true`
https://www.alfanous.org/ar/aya/?view=normal&query=%D8%A7%D9%84%D9%84%D9%87

**Comment by iTarek** [comment]
> view=normal

Why the website dose not show the view as normal by default , it was like that and something happened made it not show the sura info, also this was the case with API

**Comment by b1go** [comment]
there was latest changes that not merged into the donation button change, 
please check again

**Comment by iTarek** [comment]
> there was latest changes that not merged into the donation button change,
> please check again

Thank you, everything back yo normal, I will add the `view=normal` to my code just in case this happen again
