### ISSUE TITLE
AlFanous iOS App update we'll be ready soon

### ISSUE THREAD

**Issue by iTarek** [Alfanous-team/alfanous#535]
I hope you really like this update, I build it from scratch using SwiftUI, that's why it will work on iOS 14 and above.
I really made lot of effort to make AlFamous powerful search engine easy to use for everyone, that why I made the suggestion bar that have all the Quran words and it normalize the user words trying to get a match even if user wrote the word not exactly the same as Quran word, the suggestion bar also have the chapters, topics & subtopics, it also suggest that user search for part of the word or word root and give ready to use fields like Sura name.
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2021-07-06 at 22 12 36](https://user-images.githubusercontent.com/693715/125144912-bf9e7200-e11f-11eb-99b0-2a6caf75cadc.png)

The app also put chart for comparing words matches on Quran in easy way, and have powerful system for pages you can load more or get results by pages. 

The app is loaded with many features like ready to use complex search queries, very easy to read help with examples, full Quran if you want to check the ayah on the Mushaf, and export search as images or text.

[This is promo video](https://youtu.be/Lwj2_5ZW3jo)

If you wish to test the beta version this is [TestFlight link](https://testflight.apple.com/join/GixJwPzC)

The app is totally free, no ads, no user tracking, no third party code.

Thanks you for your help and I wish Allah give you the reward for that...
جزاكم الله خير

**Comment by b1go** [comment]
That's fine art! thank you for your efforts. 

I have some suggestions:
- we plan to host the API in cloud so I suggest to release after this so we be sure no disturbance when the app is trending
- if you can  add ident="ios-app" so we can know calls coming from this app

**Comment by iTarek** [comment]
> That's fine art! thank you for your efforts.
> 
> I have some suggestions:
> 
> * we plan to host the API in cloud so I suggest to release after this so we be sure no disturbance when the app is trending
> * if you can  add ident="ios-app" so we can know calls coming from this app

Thank you for your replay
sure I will add ident="ios-app"
You will start see it from today

But I can not delay the release it will be on the first day of Eid after 10 days from today, ان شاء الله
I have to upload it to App Store soon for release Apple may take time to review you and maybe reject it as they do most of time, so I have to be ready.
