### ISSUE TITLE
Happy Eid, AlFanous iOS app is available on the AppStore

### ISSUE THREAD

**Issue by iTarek** [Alfanous-team/alfanous#536]
السلام عليكم ورحمة الله وبركاته
Happy Eid, Amazing team of AlFanous, and all Muslims 

The iOS app is ready
https://apps.apple.com/app/id543646326

I wish you enjoy using it and I wish this small step takes Al Fanous search engine project to the next stage, you can make better API and we can make better use of it.

I hope the website takes some of the new UI/UX we introduced on the iOS app.

Like subjects, topics & subtopics section 
![IMG_C874DB1A7DD8-1](https://user-images.githubusercontent.com/693715/126228774-7709a362-fc4d-4222-b2bd-a0a3b606f581.jpeg)

Also the suggestion bar that have all the Quran words so when user type ادم you give him the correct spelling of the word, because most users will not write the word correct as it is in Quran.
![IMG_9AD710993FC2-1](https://user-images.githubusercontent.com/693715/126229018-07bbcad1-7743-4982-bf48-13e03bc919a9.jpeg)

Also give easy options for the users to search part of the word or word root
![IMG_1C66068BCE56-1](https://user-images.githubusercontent.com/693715/126229185-d26fde64-f7b6-46a8-b0f4-e589abbc7246.jpeg)

Also compare the words and give the matches on all Quran with nice chart 
![IMG_D6B4716CA4C7-1](https://user-images.githubusercontent.com/693715/126229312-832fdbda-bd52-4e4a-9eab-ee14c49d567a.jpeg)

Small tweak and yet very powerful is when the next or previous Ayah on the search is exist not show the previous and next ayah because they already there... This way users can display full Sura and be readable 
![IMG_7B94F11C94B2-1](https://user-images.githubusercontent.com/693715/126229710-19bca2c5-8a64-4de2-b476-940e1966df9d.jpeg)

My English is not that good so I can not explain how powerful the UI/UX of the app we try to target none rocket science users :)

Please use the app and if you can add download badge on the bottom of the page this will be great. Tomorrow we will publish article about it, so expect few traffic.

Thank you

**Comment by assem-ch** [comment]
Hello @iTarek , Eidek mubarek .. The UX is very amazing, we'll see how to improve the API to provide those features in a more natural way.

**Comment by iTarek** [comment]
> Hello @iTarek , Eidek mubarek .. The UX is very amazing, we'll see how to improve the API to provide those features in a more natural way.

It will be really good if you take a look at this, because I guess it's important

https://github.com/Alfanous-team/alfanous/issues/534
