### ISSUE TITLE
_

### ISSUE THREAD

**Issue by imane-mekideche** [Alfanous-team/alfanous#539]
https://github.com/Alfanous-team/alfanous/blob/590a8a91a9c99f7a8013b975416b1e31317a1f6b/store/quranic-corpus-term-of-use.txt#L1

**Comment by sneetsher** [comment]
Welcome @imane-mekideche 

Could you please elaborate more? The title is not clear (is this is a dispute or some thing?) 

What the relation/issue with Quranic Arabic Corpus (upstream use license)?
