### ISSUE TITLE
add praytimes to alfanous api

### ISSUE THREAD

**Issue by zsmahi** [Alfanous-team/alfanous#74]
add pray times to alfanous api
a simple script showing how to calculate prayer times 
https://gist.github.com/3761923

**Comment by assem-ch** [comment]
It became irrelevant now
![screen shot 2018-11-11 at 5 37 34 am](https://user-images.githubusercontent.com/315228/48309142-eb828780-e573-11e8-8d4d-4ce67b98d47f.png)
